branches:
  only:
  - master
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: julia

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - i386

julia:
  - "1.0"
  - "1"   # Latest stable release (currently "1.5")
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly

  exclude:
    # Test 32-bit only on Linux
    - arch: i386
      os: osx
    - arch: i386
      os: windows
    # Test fewer versions too
    - julia: "1.0"
      os: osx
    - julia: nightly
      os: osx
    - julia: "1.0"
      os: windows

notifications:
  webhooks: https://coveralls.io/webhook
  email: false

script:
  - julia --color=yes --check-bounds=yes etc/travis-test.jl
  # submit coverage data to a black hole server with a fake job-id,
  # and collect new coverage data on that
  - COVERALLS_URL=https://httpbingo.julialang.org/post
    julia --color=yes --code-coverage=user etc/travis-coverage.jl
  # submit coverage data *again*, this time without code coverage
  - julia --color=yes etc/travis-coverage.jl
